import { ChangeDetectionStrategy, Component, inject, OnInit, computed } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { EmployeeService } from '@core/services/employee.service';
import { ExportService } from '@core/services/export.service';
import { ToastService } from '@core/services/toast.service';
import { DialogService } from '@core/services/dialog.service';
import { AuditService } from '@core/services/audit.service';
import { AuthStateService } from '@core/auth/auth-state.service';
import { LineChartComponent } from '@shared/components/charts/line-chart/line-chart.component';
import { BarChartComponent } from '@shared/components/charts/bar-chart/bar-chart.component';
import { DoughnutChartComponent } from '@shared/components/charts/doughnut-chart/doughnut-chart.component';
import { ChartCardComponent } from '@shared/components/charts/chart-card/chart-card.component';
import { TableComponent } from '@shared/components/table/table.component';
import { IconComponent } from '@shared/components/icon/icon.component';
import { APP_ICONS } from '@core/constants/icon.constants';
import { TableColumn } from '@core/models/table.models';
import { TranslatePipe } from '@ngx-translate/core';
import { ReportsStore, ReportHistoryRow } from './reports.store';

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [
    ReactiveFormsModule, IconComponent,
    LineChartComponent, BarChartComponent, DoughnutChartComponent, ChartCardComponent,
    TableComponent, TranslatePipe
  ],
  templateUrl: './reports.component.html',
  styleUrl: './reports.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class ReportsComponent implements OnInit {
  readonly APP_ICONS = APP_ICONS;
  
  // Services & Store
  readonly store = inject(ReportsStore);
  readonly employeeService = inject(EmployeeService);
  private readonly exportService = inject(ExportService);
  private readonly toast = inject(ToastService);
  private readonly dialogService = inject(DialogService);
  private readonly auditService = inject(AuditService);
  private readonly authState = inject(AuthStateService);

  // Form controls for date filters
  readonly dateFromControl = new FormControl('');
  readonly dateToControl = new FormControl('');
  readonly deptControl = new FormControl('');

  // Expose store signals directly to template
  readonly loading = this.store.loading;
  readonly error = this.store.error;
  readonly analytics = this.store.analytics;
  readonly lastRefresh = this.store.lastRefresh;
  readonly exportsCount = this.store.exportsCount;
  readonly scheduledReports = this.store.scheduledReports;
  readonly historyRows = this.store.historyRows;

  // Executive KPI stats delegated to store
  readonly totalEmployees = this.store.totalEmployees;
  readonly attendanceRate = this.store.attendanceRate;
  readonly taskCompletion = this.store.taskCompletion;
  readonly growthRate = this.store.growthRate;

  // Report categories definitions
  readonly reportCategories = [
    { id: 'workforce', name: 'Workforce Roster', icon: APP_ICONS.USERS, desc: 'Detailed employee demographics, department alignment, and salaries.' },
    { id: 'attendance', name: 'Attendance Record', icon: APP_ICONS.CALENDAR, desc: 'Summary of team attendances, leaves, and overall present rates.' },
    { id: 'performance', name: 'Performance Metrics', icon: APP_ICONS.TRENDING_UP, desc: 'High-level department task completions and performance levels.' },
    { id: 'audit', name: 'Access Audit Logs', icon: APP_ICONS.AUDIT, desc: 'Detailed log reports tracing authentication activities and security logs.' },
    { id: 'compliance', name: 'Compliance Checklist', icon: APP_ICONS.SETTINGS, desc: 'Tracks configurations, MFA enrollments, and security level policies.' },
    { id: 'financial', name: 'Financial Roster', icon: APP_ICONS.REPORTS, desc: 'Salary distribution details, department payroll aggregates, and structures.' }
  ];

  // Report History columns
  readonly historyColumns: TableColumn<ReportHistoryRow>[] = [
    { key: 'name', label: 'Report Name' },
    { key: 'generatedBy', label: 'Generated By' },
    { key: 'createdAt', label: 'Generated On' },
    { key: 'format', label: 'Format' },
    { key: 'status', label: 'Status' }
  ];

  constructor() {
    this.dateFromControl.valueChanges.subscribe(() => this.triggerFilterLoading());
    this.dateToControl.valueChanges.subscribe(() => this.triggerFilterLoading());
    this.deptControl.valueChanges.subscribe(() => this.triggerFilterLoading());
  }

  ngOnInit(): void {
    this.store.loadReports();
  }

  private triggerFilterLoading(): void {
    this.store.loadReports(false);
  }

  generateReport(): void {
    this.store.loadReports(true, () => {
      this.toast.showToast('Analytics indicators refreshed and generated successfully', 'success');
    });
  }

  generateCategoryReport(catId: string): void {
    this.dialogService.confirm({
      title: 'Generate Roster Report',
      message: `Are you sure you want to compile and download the current ${catId} report?`,
      variant: 'info',
      icon: APP_ICONS.REPORTS
    }).then(confirmed => {
      if (confirmed) {
        // Run report generation logic
        if (catId === 'workforce' || catId === 'financial') {
          const list = this.employeeService.employees().map(e => ({
            Code: e.employeeCode,
            Name: `${e.firstName} ${e.lastName}`,
            Email: e.email,
            Department: e.department,
            Designation: e.designation,
            Location: e.location,
            Joined: e.joinedAt,
            Salary: e.salary
          }));
          this.exportService.downloadCsv(list, `${catId}-report`);
        } else if (catId === 'audit') {
          const logs = this.auditService.logs().map(l => ({
            Timestamp: l.createdAt,
            Actor: l.actor,
            Action: l.action,
            Entity: l.entity,
            Severity: l.severity,
            IP: l.ipAddress
          }));
          this.exportService.downloadCsv(logs, 'audit-compliance-report');
        } else {
          const mockData = [
            { Metric: 'Overall Efficiency', Target: '95.0%', Actual: '96.4%', Status: 'Compliant' },
            { Metric: 'MFA Enrollment', Target: '100%', Actual: '80%', Status: 'Pending' },
            { Metric: 'Database Backups', Target: 'Daily', Actual: 'Completed Today', Status: 'Success' }
          ];
          this.exportService.downloadExcel(mockData, `${catId}-compliance-report`);
        }

        // Add history row in the store
        const newRow: ReportHistoryRow = {
          id: `rh-${crypto.randomUUID()}`,
          name: `${catId.charAt(0).toUpperCase() + catId.slice(1)} Report Summary`,
          generatedBy: this.authState.user()?.fullName ?? 'Avery Admin',
          createdAt: new Date().toISOString().replace('T', ' ').substring(0, 16),
          format: catId === 'financial' || catId === 'workforce' || catId === 'audit' ? 'CSV' : 'Excel',
          status: 'Completed'
        };
        this.store.addHistoryRow(newRow);
        this.toast.showToast('Report generated and downloaded successfully', 'success');
      }
    });
  }

  exportGeneral(format: 'csv' | 'excel' | 'pdf'): void {
    const employees = this.employeeService.employees();
    if (format === 'csv') {
      this.exportService.downloadCsv(employees, 'workforce-general-export');
      this.toast.showToast('General workforce roster exported as CSV', 'success');
    } else if (format === 'excel') {
      this.exportService.downloadExcel(employees, 'workforce-general-sheet');
      this.toast.showToast('General workforce roster exported as Excel sheet', 'success');
    } else {
      window.print();
    }
    this.store.incrementExports();
  }
}
