import { ChangeDetectionStrategy, Component, inject, signal, computed } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { toSignal } from '@angular/core/rxjs-interop';
import { catchError, of } from 'rxjs';
import { AnalyticsService } from '@core/services/analytics.service';
import { EmployeeService } from '@core/services/employee.service';
import { ExportService } from '@core/services/export.service';
import { ToastService } from '@core/services/toast.service';
import { DialogService } from '@core/services/dialog.service';
import { AuditService } from '@core/services/audit.service';
import { AuthStateService } from '@core/auth/auth-state.service';
import { LineChartComponent } from '@shared/components/charts/line-chart/line-chart.component';
import { BarChartComponent } from '@shared/components/charts/bar-chart/bar-chart.component';
import { DoughnutChartComponent } from '@shared/components/charts/doughnut-chart/doughnut-chart.component';
import { ChartCardComponent } from '@shared/components/charts/chart-card/chart-card.component';
import { TableComponent } from '@shared/components/table/table.component';
import { IconComponent } from '@shared/components/icon/icon.component';
import { APP_ICONS } from '@core/constants/icon.constants';
import { TableColumn } from '@core/models/table.models';
import { TranslatePipe } from '@ngx-translate/core';

interface ReportHistoryRow {
  id: string;
  name: string;
  generatedBy: string;
  createdAt: string;
  format: string;
  status: string;
}

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [
    ReactiveFormsModule, IconComponent,
    LineChartComponent, BarChartComponent, DoughnutChartComponent, ChartCardComponent,
    TableComponent, TranslatePipe
  ],
  templateUrl: './reports.component.html',
  styleUrl: './reports.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class ReportsComponent {
  readonly APP_ICONS = APP_ICONS;
  
  // Services
  readonly employeeService = inject(EmployeeService);
  private readonly analyticsService = inject(AnalyticsService);
  private readonly exportService = inject(ExportService);
  private readonly toast = inject(ToastService);
  private readonly dialogService = inject(DialogService);
  private readonly auditService = inject(AuditService);
  private readonly authState = inject(AuthStateService);

  // Form controls for date filters
  readonly dateFromControl = new FormControl('');
  readonly dateToControl = new FormControl('');
  readonly deptControl = new FormControl('');

  // Local state properties
  readonly lastRefresh = signal<string>(new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', second: '2-digit' }));
  readonly exportsCount = signal<number>(8);

  // Analytics signal
  readonly analytics = toSignal(this.analyticsService.adminAnalytics().pipe(catchError(() => of(null))));

  // Report categories data
  readonly reportCategories = [
    { id: 'workforce', name: 'Workforce Roster', icon: APP_ICONS.USERS, desc: 'Detailed employee demographics, department alignment, and salaries.' },
    { id: 'attendance', name: 'Attendance Record', icon: APP_ICONS.CALENDAR, desc: 'Summary of team attendances, leaves, and overall present rates.' },
    { id: 'performance', name: 'Performance Metrics', icon: APP_ICONS.TRENDING_UP, desc: 'High-level department task completions and performance levels.' },
    { id: 'audit', name: 'Access Audit Logs', icon: APP_ICONS.AUDIT, desc: 'Detailed log reports tracing authentication activities and security logs.' },
    { id: 'compliance', name: 'Compliance Checklist', icon: APP_ICONS.SETTINGS, desc: 'Tracks configurations, MFA enrollments, and security level policies.' },
    { id: 'financial', name: 'Financial Roster', icon: APP_ICONS.REPORTS, desc: 'Salary distribution details, department payroll aggregates, and structures.' }
  ];

  // Scheduled reports UI state list
  readonly scheduledReports = signal([
    { name: 'Weekly Attendance Summary', frequency: 'Every Friday at 17:00', nextRun: '2026-06-12 17:00', status: 'Active' },
    { name: 'Monthly Workforce Demographics', frequency: 'First of the Month at 08:00', nextRun: '2026-07-01 08:00', status: 'Active' },
    { name: 'Quarterly Security Compliance Audit', frequency: 'First Day of Quarter at 00:00', nextRun: '2026-07-01 00:00', status: 'Paused' }
  ]);

  // Report History configurations
  readonly historyColumns: TableColumn<ReportHistoryRow>[] = [
    { key: 'name', label: 'Report Name' },
    { key: 'generatedBy', label: 'Generated By' },
    { key: 'createdAt', label: 'Generated On' },
    { key: 'format', label: 'Format' },
    { key: 'status', label: 'Status' }
  ];

  readonly historyRows = signal<ReportHistoryRow[]>([
    { id: 'rh1', name: 'Workforce Roster Demographics', generatedBy: 'Avery Admin', createdAt: '2026-06-07 14:23', format: 'CSV', status: 'Completed' },
    { id: 'rh2', name: 'Monthly Security & Access Audit', generatedBy: 'Avery Admin', createdAt: '2026-06-05 09:11', format: 'Excel', status: 'Completed' },
    { id: 'rh3', name: 'Employee Utilization & Attendance', generatedBy: 'System', createdAt: '2026-06-01 00:00', format: 'PDF', status: 'Completed' }
  ]);

  // Executive KPI stats derived from live services
  readonly totalEmployees = computed(() => this.employeeService.employees().length);
  readonly attendanceRate = signal<string>('96.4%');
  readonly taskCompletion = signal<string>('88.2%');
  readonly growthRate = signal<string>('+14.8%');

  readonly loading = signal(false);

  constructor() {
    this.dateFromControl.valueChanges.subscribe(() => this.triggerFilterLoading());
    this.dateToControl.valueChanges.subscribe(() => this.triggerFilterLoading());
    this.deptControl.valueChanges.subscribe(() => this.triggerFilterLoading());
  }

  private triggerFilterLoading(): void {
    this.loading.set(true);
    setTimeout(() => {
      this.loading.set(false);
    }, 400);
  }

  generateReport(): void {
    this.loading.set(true);
    setTimeout(() => {
      this.lastRefresh.set(new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', second: '2-digit' }));
      this.toast.showToast('Analytics indicators refreshed and generated successfully', 'success');
      this.loading.set(false);
    }, 600);
  }

  generateCategoryReport(catId: string): void {
    this.dialogService.confirm({
      title: 'Generate Roster Report',
      message: `Are you sure you want to compile and download the current ${catId} report?`,
      variant: 'info',
      icon: APP_ICONS.REPORTS
    }).then(confirmed => {
      if (confirmed) {
        this.loading.set(true);
        setTimeout(() => {
          if (catId === 'workforce' || catId === 'financial') {
            const list = this.employeeService.employees().map(e => ({
              Code: e.employeeCode,
              Name: `${e.firstName} ${e.lastName}`,
              Email: e.email,
              Department: e.department,
              Designation: e.designation,
              Location: e.location,
              Joined: e.joinedAt,
              Salary: e.salary
            }));
            this.exportService.downloadCsv(list, `${catId}-report`);
          } else if (catId === 'audit') {
            const logs = this.auditService.logs().map(l => ({
              Timestamp: l.createdAt,
              Actor: l.actor,
              Action: l.action,
              Entity: l.entity,
              Severity: l.severity,
              IP: l.ipAddress
            }));
            this.exportService.downloadCsv(logs, 'audit-compliance-report');
          } else {
            // Mock trigger
            const mockData = [
              { Metric: 'Overall Efficiency', Target: '95.0%', Actual: '96.4%', Status: 'Compliant' },
              { Metric: 'MFA Enrollment', Target: '100%', Actual: '80%', Status: 'Pending' },
              { Metric: 'Database Backups', Target: 'Daily', Actual: 'Completed Today', Status: 'Success' }
            ];
            this.exportService.downloadExcel(mockData, `${catId}-compliance-report`);
          }

          // Add history row
          const newRow: ReportHistoryRow = {
            id: `rh-${crypto.randomUUID()}`,
            name: `${catId.charAt(0).toUpperCase() + catId.slice(1)} Report Summary`,
            generatedBy: this.authState.user()?.fullName ?? 'Avery Admin',
            createdAt: new Date().toISOString().replace('T', ' ').substring(0, 16),
            format: catId === 'financial' || catId === 'workforce' || catId === 'audit' ? 'CSV' : 'Excel',
            status: 'Completed'
          };
          this.historyRows.update(rows => [newRow, ...rows]);
          this.exportsCount.update(c => c + 1);
          this.toast.showToast('Report generated and downloaded successfully', 'success');
          this.loading.set(false);
        }, 800);
      }
    });
  }

  exportGeneral(format: 'csv' | 'excel' | 'pdf'): void {
    const employees = this.employeeService.employees();
    this.loading.set(true);
    setTimeout(() => {
      if (format === 'csv') {
        this.exportService.downloadCsv(employees, 'workforce-general-export');
        this.toast.showToast('General workforce roster exported as CSV', 'success');
      } else if (format === 'excel') {
        this.exportService.downloadExcel(employees, 'workforce-general-sheet');
        this.toast.showToast('General workforce roster exported as Excel sheet', 'success');
      } else {
        window.print();
      }
      this.exportsCount.update(c => c + 1);
      this.loading.set(false);
    }, 500);
  }
}
